#!/bin/bash

ARGS=$@

if [ ! -d /etc/pcsx-redux ]; then
    sudo mkdir /etc/pcsx-redux
fi
cd /etc/pcsx-redux

launch()
{
    DISPLAY=$1 pcsx-redux $ARGS
    if [ $? = "0" ]; then
        exit 0
    fi
}

echo "Starting pcsx-redux..."
launch $DISPLAY

for f in /tmp/.X11-unix/*; do
    DSP=:$(basename ${f//X/})
    if [ $DISPLAY = $DSP ]; then
        continue
    fi

    echo "DISPLAY env var seems to be invalid! Attempting to use $DSP instead..."
    launch $DSP
done
