name: Build Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: apt-get update && apt-get install -y build-essential g++-mipsel-linux-gnu python3 curl unzip gzip p7zip-full cmake
      - name: Install ARMIPS
        run: |
          set -e

          git clone --recursive https://github.com/Kingcom/armips.git
          mkdir -p armips/build && cd armips/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          cp armips /usr/local/bin
      - name: Install Nugget
        run: git clone --recursive https://github.com/pcsx-redux/nugget.git /usr/local/nugget
      - name: Install PsyQ
        run: |
          set -e
          
          wget http://psx.arthus.net/sdk/Psy-Q/psyq-4.7-converted-full.7z
          7z x psyq-4.7-converted-full.7z -o/usr/local/psyq
          chmod -R 777 /usr/local/psyq
          rm -rf psyq-4.7-converted-full.7z
      - name: Install mkpsxiso
        run: |
          set -e

          wget https://github.com/Lameguy64/mkpsxiso/releases/download/v2.04/mkpsxiso-2.04-Linux.zip
          unzip mkpsxiso-2.04-Linux.zip -d /usr/local/
          mv /usr/local/mkpsxiso* /usr/local/mkpsxiso
          ln -s /usr/local/mkpsxiso/bin/mkpsxiso /usr/local/bin/mkpsxiso
          ln -s /usr/local/mkpsxiso/bin/dumpsxiso /usr/local/bin/dumpsxiso
          chmod +x /usr/local/bin/mkpsxiso /usr/local/bin/dumpsxiso
          rm -rf mkpsxiso-2.04-Linux.zip

      - name: Build Binaries
        run: make all

      # - name: Archive Binaries
      #   run: tar -czf bin.tar.gz **/*.ps-exe
      - name: Upload Binaries
        run: |
          for f in **/*.ps-exe; do
            curl --header 'authorization: Bearer ${{ secrets.PACKAGE_PASS }}' \
              --upload-file $f \
              $GITHUB_SERVER_URL/api/packages/$GITHUB_REPOSITORY_OWNER/generic/psx-bin/$GITHUB_REF_NAME/$(basename $f)
          done

      - name: Upload 06 JoyPad ISO
        run: |
          curl --header 'authorization: Bearer ${{ secrets.PACKAGE_PASS }}' \
            --upload-file 06-joypad/GAME.iso \
            $GITHUB_SERVER_URL/api/packages/$GITHUB_REPOSITORY_OWNER/generic/psx-iso/$GITHUB_REF_NAME/joypad.iso
